### PR TITLE
Flag changes to match bootkube change

### PR DESCRIPTION
**Pull request by diegs**
Flag changes for https://github.com/kubernetes-incubator/bootkube/pull/437

### CODE REVIEW

**Comment by yifan-gu** [comment]
cc @pbx0

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by diegs** [comment]
Thanks for taking a look, can one of you please merge too?

**Comment by pbx0** [comment]
@diegs: Sure, just waiting on the test to pass then i'll merge.

**Pull request merged**
