### PR TITLE
Add feature template

### PR DESCRIPTION
**Pull request by ashcrow**
Adds a feature template per meeting.

/cc @darkmuggle @ajeddeloh @lucab @vrutkovs @arithx

### CODE REVIEW

**Comment by ashcrow** [comment]
Travis failure is unrelated

**Comment by arithx** [comment]
Testing a fix in #1053 to unblock this

**Comment by bgilbert** [comment]
This will cause the "New issue" button to present a UI similar to [this](https://github.com/coreos/ignition/issues/new/choose), but with only one row.  So if we're adding a feature template, we should add a bug template too.

**Comment by arithx** [comment]
#1053 is merged, if you rebase on top of current master the travis failure should go away (as it will now correctly use the cached `vendor/` directory instead of attempting to fetch vendored libraries)

**Comment by ashcrow** [comment]
Rebased and added

**Pull request merged**
