### PR TITLE
Support for running many etcd tests in kola

### PR DESCRIPTION
**Pull request by pbx0**
/cc @marineam

### CODE REVIEW

**Comment by marineam** [comment]
The `"$public_ipv4"` goo is included in the StartJournal commit but the change log doesn't mention it.

**Comment by pbx0** [comment]
Thanks for the feedback, I updated the branch with the changes. I seem to have squashed most of the pull request's comments in the process. 

/cc @marineam @crawford

**Comment by marineam** [comment]
[LGTM](http://www.lgtm.in/i/8Y28PluXp)

**Comment by marineam** [comment]
btw, on the comments, that's just one awkward bit about PRs, if comments are made on individual commits like we did then replacing those commits similarly drops the comments from the PR. Commenting on the big diff in the PR will keep the comments associated but then the reviewer cannot view the diff split into the logical chunks commits provide. No particular rule to do things one way or the other but something to keep in mind.

**Comment by pbx0** [comment]
Updated branch with @crawford 's comments. The go-routine responsible for journal output will be exit when the machine does. A stop mechanism could be added in the future.

**Comment by crawford** [comment]
LGTM

**Pull request merged**
