### PR TITLE
Add authentication test

### PR DESCRIPTION
**Pull request by mjg59**
Ensure that ssh login attempts with invalid credentials are rejected

### CODE REVIEW

**Comment by marineam** [comment]
Looks good, one nit though, perhaps "Credentialed" should actually be more specifically "Password" since I could also see utility in hitting PAM directly via challenge/response/interactive mode and so on later on.

**Comment by marineam** [comment]
Travis claims you need to gofmt as well

**Comment by crawford** [comment]
+1 for Password instead of Credentialed.

**Comment by crawford** [comment]
Update commit message, otherwise LGTM.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
