### PR TITLE
fix godeps

### PR DESCRIPTION
**Pull request by mischief**
godep not behaving very well with code.google.com repos, so i manually disentangled it.

i tested godep restore and godep save -r ./... cycle, and it seems to work ok now, except for github.com/coreos/yaml:

```
$ godep restore
godep save -r ./...# cd /tmp/gopath2/src/github.com/coreos/yaml; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
package github.com/coreos/yaml: exit status 1
godep: restore: exit status 1
```

but that's another matter.

### CODE REVIEW

**Comment by pbx0** [comment]
Looks like github.com/coreos/etcd/pkg/metrics and pkg/flags were dropped in the 2nd commit according to the godep json file. Just checking that this was intentional, if so, LGTM.

**Comment by mischief** [comment]
@pbx0 are those packages needed somewhere? mantle seemed to build fine with the updates in this pr.

**Comment by pbx0** [comment]
I didn't check if they were used but it sounds like its fine. Just checking because godeps

**Comment by marineam** [comment]
LGTM as far as I can tell ;-)

**Comment by mischief** [comment]
well, i merged it, but github doesn't think i did.

**Pull request closed without merging**
