### PR TITLE
Rework AnonymousFile, add PrivateFile

### PR DESCRIPTION
**Pull request by marineam**
After actually starting to use this I changed my mind from what I originally wrote back in December.

### CODE REVIEW

**Comment by crawford** [comment]
"awkard" in 0dd09ba

**Comment by crawford** [comment]
What is "sektrit" in 8588871?

**Comment by crawford** [comment]
Code looks good.

**Comment by marineam** [comment]
Commit messages updated

**Comment by crawford** [comment]
LGTM

**Pull request merged**
