### PR TITLE
ore+plume: replace cloud/storage with api/storage package.

### PR DESCRIPTION
**Pull request by marineam**
The cloud/storage package is documented as experimental and has been significantly refactored since this code was written. Since this code needs to be reworked anyway may as well switch to the somewhat more stable api/storage package.

There is a far amount of code duplication in these commands but fixing that is left for another day.

### CODE REVIEW

**Comment by marineam** [comment]
Note: build tested, I still need to take some time to actually upload stuff to GCE

**Comment by marineam** [comment]
Ok, upload tests check out :-D

**Comment by mischief** [comment]
lgtm

**Comment by pbx0** [comment]
`There is a far amount of code duplication in these commands but fixing that is left for another day.`

Agreed! I've wanted to address https://github.com/coreos/mantle/issues/164 for some time

**Pull request merged**
