### PR TITLE
kola: parallelize tests executed

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by mischief** [comment]
i have etcd1 tests disabled here because they fail and take a long time.

before:
```
$ time ./bin/kola --platform aws --aws-key mischief --aws-type m3.medium --aws-ami ami-c35c9987 run                                                                                      
2015-09-19T03:36:38Z kola: === RUN Etcd2Discovery on aws
client: no endpoints available
2015-09-19T03:37:53Z kola: --- PASS: Etcd2Discovery on aws (75.028s)
2015-09-19T03:37:53Z kola: === RUN NFSv4 on aws
2015-09-19T03:39:59Z kola: --- PASS: NFSv4 on aws (125.838s)
2015-09-19T03:39:59Z kola: === RUN RktInstall on aws
rkt directory structure successfully created.
2015-09-19T03:40:58Z kola: --- PASS: RktInstall on aws (59.003s)
2015-09-19T03:40:58Z kola: === RUN coretestsLocal on aws
2015-09-19T03:42:09Z kola/tests/coretest: running ServicesActive...
2015-09-19T03:42:10Z kola/tests/coretest: running RandomUUID...
2015-09-19T03:42:10Z kola/tests/coretest: running CloudConfig...
2015-09-19T03:42:11Z kola/tests/coretest: running Script...
2015-09-19T03:42:11Z kola/tests/coretest: running PortSSH...
2015-09-19T03:42:11Z kola/tests/coretest: running DbusPerms...
2015-09-19T03:42:12Z kola/tests/coretest: running Symlink...
2015-09-19T03:42:12Z kola/tests/coretest: running UpdateEngineKeys...
2015-09-19T03:42:12Z kola/tests/coretest: running Useradd...
2015-09-19T03:42:13Z kola/tests/coretest: running ReadOnly...
2015-09-19T03:42:14Z kola: --- PASS: coretestsLocal on aws (75.278s)
2015-09-19T03:42:14Z kola: === RUN coretestsCluster on aws
2015-09-19T03:44:00Z kola/tests/coretest: running EtcdUpdateValue...
2015-09-19T03:44:02Z kola/tests/coretest: running FleetctlListMachines...
2015-09-19T03:44:04Z kola/tests/coretest: running FleetctlRunService...
2015-09-19T03:44:10Z kola: --- PASS: coretestsCluster on aws (116.674s)
2015-09-19T03:44:10Z kola: === RUN coretestsInternetLocal on aws
2015-09-19T03:45:26Z kola/tests/coretest: running UpdateEngine...
2015-09-19T03:45:26Z kola/tests/coretest: running DockerPing...
2015-09-19T03:45:37Z kola/tests/coretest: running DockerEcho...
2015-09-19T03:45:38Z kola/tests/coretest: running NTPDate...
2015-09-19T03:45:47Z kola: --- PASS: coretestsInternetLocal on aws (97.032s)
2015-09-19T03:45:47Z kola: === RUN FleetProxy on aws
2015-09-19T03:48:08Z kola: --- PASS: FleetProxy on aws (140.448s)
2015-09-19T03:48:08Z kola: === RUN NFSv3 on aws
2015-09-19T03:50:16Z kola: --- PASS: NFSv3 on aws (127.905s)
2015-09-19T03:50:16Z kola: 8 passed 0 failed out of 8 total

real    13m37.246s
user    0m12.760s
sys     0m0.460s
```

after:

```
$ time ./bin/kola --platform aws --parallel 8 --aws-key mischief --aws-type m3.medium --aws-ami ami-c35c9987 run                                                                         
2015-09-19T03:28:31Z kola: === RUN RktInstall on aws
2015-09-19T03:28:33Z kola: === RUN coretestsLocal on aws
2015-09-19T03:28:35Z kola: === RUN Etcd2Discovery on aws
2015-09-19T03:28:37Z kola: === RUN coretestsCluster on aws
2015-09-19T03:28:39Z kola: === RUN coretestsInternetLocal on aws
2015-09-19T03:28:41Z kola: === RUN FleetProxy on aws
2015-09-19T03:28:43Z kola: === RUN NFSv3 on aws
2015-09-19T03:28:45Z kola: === RUN NFSv4 on aws
rkt directory structure successfully created.
2015-09-19T03:29:34Z kola: --- PASS: RktInstall on aws (62.752s)
client: no endpoints available
2015-09-19T03:30:03Z kola: --- PASS: Etcd2Discovery on aws (87.304s)
2015-09-19T03:30:09Z kola/tests/coretest: running RandomUUID...
2015-09-19T03:30:09Z kola/tests/coretest: running Useradd...
2015-09-19T03:30:09Z kola/tests/coretest: running CloudConfig...
2015-09-19T03:30:10Z kola/tests/coretest: running DbusPerms...
2015-09-19T03:30:10Z kola/tests/coretest: running Symlink...
2015-09-19T03:30:11Z kola/tests/coretest: running UpdateEngineKeys...
2015-09-19T03:30:11Z kola/tests/coretest: running Script...
2015-09-19T03:30:11Z kola/tests/coretest: running PortSSH...
2015-09-19T03:30:11Z kola/tests/coretest: running ServicesActive...
2015-09-19T03:30:12Z kola/tests/coretest: running ReadOnly...
2015-09-19T03:30:12Z kola: --- PASS: coretestsLocal on aws (98.869s)
2015-09-19T03:30:23Z kola/tests/coretest: running UpdateEngine...
2015-09-19T03:30:23Z kola/tests/coretest: running DockerPing...
2015-09-19T03:30:33Z kola/tests/coretest: running DockerEcho...
2015-09-19T03:30:33Z kola/tests/coretest: running NTPDate...
2015-09-19T03:30:40Z kola: --- PASS: coretestsInternetLocal on aws (121.268s)
2015-09-19T03:30:41Z kola/tests/coretest: running FleetctlRunService...
2015-09-19T03:30:45Z kola: --- PASS: NFSv3 on aws (122.035s)
2015-09-19T03:30:47Z kola/tests/coretest: running EtcdUpdateValue...
2015-09-19T03:30:50Z kola/tests/coretest: running FleetctlListMachines...
2015-09-19T03:30:51Z kola: --- PASS: coretestsCluster on aws (134.036s)
2015-09-19T03:31:00Z kola: --- PASS: FleetProxy on aws (139.044s)
2015-09-19T03:31:10Z kola: --- PASS: NFSv4 on aws (144.694s)
2015-09-19T03:31:10Z kola: 8 passed 0 failed out of 8 total

real    2m38.731s
user    0m12.360s
sys     0m0.460s
```

**Comment by pbx0** [comment]
I think I remember the discussion on this being about possibly reworking this to not have a limit so much on the # of test running concurrently but the # of vms running concurrently?

Since you don't know how many vms will spawn before starting a test, it seems like the only option here is to use heuristics to launch X many tests concurrently based on the VM limit.  You could launch a test at a time and poll to see how many instances it creates before deciding to launch another, but its hard to know when its done spawning vms. 

So I'm more in favor of how it is now unless there is a better way to limit this by vm.

**Comment by pbx0** [comment]
Current code LGTM, pending deciding on way to do this.

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Pull request merged**
