### PR TITLE
platform: have qemu fall back to tcg when kvm is not available

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
alternative to this would be add an explicit flag to toggle use of kvm.

**Comment by mischief** [comment]
retest this please

**Comment by marineam** [comment]
Making the timeouts work for tcg is probably going to be needed for testing arm64.

**Pull request closed without merging**
