### PR TITLE
sdk: add new image signing sub-key B58844F1

### PR DESCRIPTION
**Pull request by marineam**
pub   4096R/93D2DCB4 2013-09-06
uid       [ unknown] CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>
sub   4096R/74E7E361 2013-09-06 [expired: 2014-09-06]
sub   4096R/E5676EFC 2014-09-08 [expired: 2015-09-08]
sub   4096R/1CB5FA26 2015-08-31 [expires: 2017-08-30]
sub   4096R/B58844F1 2015-11-20 [expires: 2016-11-19]

### CODE REVIEW

**Comment by mischief** [comment]
is this pubkey available over HTTPS somewhere?

**Comment by mischief** [comment]
maybe add a comment with a canonical url to the pubkey on coreos.com?

**Comment by marineam** [comment]
@mischief comment updated, url added

**Comment by mischief** [comment]
lgtm

**Pull request merged**
