### PR TITLE
kola: disable PodmanPing and add PodmanWgetHead in fcos.internet

### PR DESCRIPTION
**Pull request by jlebon**
It doesn't play well with `cosa kola` in OpenShift. We should enable it
only when we're not on qemu-unpriv. We do want the `PodmanEcho` test
though.

### CODE REVIEW

**Comment by lucab** [comment]
LGTM.
I'd still like to have some basic container networking test. What about turning this into a `busybox wget --spider http://fedoraproject.org/static/hotspot.txt` instead of a ping? (as a followup)

**Comment by jlebon** [comment]
> What about turning this into a `busybox wget --spider http://fedoraproject.org/static/hotspot.txt` instead of a ping? (as a followup)

Good idea, done!

**Comment by jlebon** [comment]
Hmm, although... feels like it'd belong better in `tests/podman/podman.go` instead? Ehhh... I can do this if folks prefer.

**Comment by lucab** [comment]
@jlebon test seems fine there, I guess the idea is that we test 1) host network via pulling 2) namespace network via wget. A `go fmt` pass is missing though.

**Comment by lucab** [comment]
@jlebon new logic sounds good too. Feel feel to adjust title/comments and merge on your own.

**Comment by jlebon** [comment]
Thanks for the review and suggestion!

**Pull request merged**
