### PR TITLE
network/ntp: hide example ntpd main pkg

### PR DESCRIPTION
**Pull request by pbx0**

### CODE REVIEW

**Comment by mischief** [comment]
can't you simply rename ntpd.go to example_ntpd.go?

**Comment by mischief** [comment]
a la https://blog.golang.org/examples

**Comment by pbx0** [comment]
It doesn't terminate nicely like an example would and simply changing the name to example_ntpd.go doesn't make go tools ignore it:
`Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".`
I could change its main to `ExampleNTPD()` and its package to ntpd, but then its dead code and not suitable for use as an Example in the go sense.

**Comment by pbx0** [comment]
reworked the naming a bit

**Comment by mischief** [comment]
lgtm

**Pull request merged**
