### PR TITLE
kola: add systemd journal gatewayd/remote test

### PR DESCRIPTION
**Pull request by mischief**
this test will not pass until we fix libmicrohttpd, wrt coreos/bugs#919

### CODE REVIEW

**Comment by mischief** [comment]
also depends on coreos/bugs#928 being fixed

**Comment by mischief** [comment]
with the libmicrohttpd and systemd fixes applied, this test will pass as long as we give journalctl an explicit journal file argument.

```
core@853b72d6 ~ $ sudo journalctl _HOSTNAME=gateway -t core --file /var/log/journal/remote/remote-10.0.0.2:19531.journal 
-- Logs begin at Fri 2015-10-16 00:48:42 UTC, end at Fri 2015-10-16 00:48:55 UTC. --
Oct 16 00:48:55 gateway core[713]: supercalifragilisticexpialidocious
```

**Comment by mischief** [comment]
fixes #144

**Comment by pbx0** [comment]
LGTM. 

Why not define a machine and the cloud config in the registry though? No special setup seems required here.

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Pull request merged**
