### PR TITLE
sdk: retry on download failures

### PR DESCRIPTION
**Pull request by pbx0**
See: https://github.com/coreos/mantle/pull/143

@marineam

### CODE REVIEW

**Comment by marineam** [comment]
I think everything in `DownloadFile` short of the mkdir should be a private function that gets wrapped with Retry. As-is retries will make the same full or partial request instead of making use of anything that did get downloaded on the previous attempt. Letting the retries jump forward would actually be sufficient to make things succeed even in the face of our troublesome network card :)

**Comment by marineam** [comment]
Wrapping most of the code also avoids the extra nesting this version has.

**Comment by pbx0** [comment]
@marineam PTAL. I expanded the scope of the retry so it resumes whatever was copied in the first try.

I didn't split it into a private function simply because I needed a nested closure to make util.Retry useful anyway (`func() error` signature). I could just as easily write my own retry loop and split into a private function as well. Any preference?

**Comment by marineam** [comment]
@pb I'd rather avoid the extra nesting but you can wrap the call to the private function in a one line closure to get both things done.

**Comment by pbx0** [comment]
oh right, just wrap the private func:  @marineam  PTAL, no more extra nesting

**Comment by marineam** [comment]
LGTM

**Pull request merged**
