### PR TITLE
kola: Test fleet against a unit with a long line

### PR DESCRIPTION
**Pull request by chancez**
Validates the fix in https://github.com/coreos/fleet/pull/1375 by ensuring
fleet does not allow submission of unit file with a line too long for
systemd to handle.

### CODE REVIEW

**Comment by ecnahc515** [comment]
This *should* probably fail on the current build of CoreOS, but once  https://github.com/coreos/fleet/pull/1375 merges this should pass.

CC @mischief

**Comment by ecnahc515** [comment]
@pbx0 Updated the machineID code.

**Comment by pbx0** [comment]
LGTM, it fails as its designed to on current images. Lets wait to merge this until we are releasing an OS build that has the fix so our jenkins builds don't fail until then.

**Comment by mischief** [comment]
@ecnahc515 can you rebase this?

**Comment by ecnahc515** [comment]
@mischief Done.

**Comment by ecnahc515** [comment]
I'm not really sure what to do about this. Perhaps the fleet it's using doesn't reject units with long lines, but the test should be correct.

**Comment by euank** [comment]
I'm closing this since it's been dead for so long.

Please re-open or submit a new PR if there's still a desire to get this in.

**Pull request closed without merging**
