### PR TITLE
kola/tests/locksmith: properly test locksmith

### PR DESCRIPTION
**Pull request by crawford**
Using coreos-cloudinit to configure and start locksmith properly
exercises the codepath that is encountered in the field. I have no idea
why this test was originally implemented this way, but this new
implementation is more inline with what is actually done.

This now catches https://github.com/coreos/bugs/issues/1562 and https://github.com/coreos/bugs/issues/1588.

### CODE REVIEW

**Comment by crawford** [comment]
Jenkins failure is due to it testing against 1180.0.0 (expected). I asked it to retest against 1185.0.0.

**Comment by crawford** [comment]
:/ The status wasn't updated. Here is the new test result: https://jenkins.coreos.systems/job/kola-dev-qemu/505/.

**Comment by marineam** [comment]
@crawford to get the status to update you need to trigger the rebuild from here instead of jenkins.

**Comment by marineam** [comment]
retest this please

**Pull request merged**
