### PR TITLE
pluton/tests/bootkube: Update API server delete test with the new labels.

### PR DESCRIPTION
**Pull request by yifan-gu**
cc @pbx0 @squat

Ref https://github.com/kubernetes-incubator/bootkube/pull/422

### CODE REVIEW

**Comment by yifan-gu** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
@yifan-gu Test is in line for testing, so lets wait until that finishes. LGTM otherwise though.

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Comment by pbx0** [comment]
coreosbot run pluton tests

**Pull request merged**
