### PR TITLE
Fetch upstream k8s versions programmatically.

### PR DESCRIPTION
**Pull request by diegs**
Rather than hardcoding versions when fetching kubectl from the web we
can curl them from a known URL scheme.

### CODE REVIEW

**Comment by diegs** [comment]
cc @pbx0

**Comment by pbx0** [comment]
Would this PR also solve your needs? https://github.com/coreos/mantle/pull/601

**Comment by diegs** [comment]
Yes, I thought I saw something fly by :)

**Comment by diegs** [comment]
Abandoning since #601 does this more nicely.

**Pull request closed without merging**
